apiVersion: apps/v1
kind: Deployment
metadata:
  name: claudeosaar-api
  namespace: claudeosaar
  labels:
    app: claudeosaar-api
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: claudeosaar-api
  template:
    metadata:
      labels:
        app: claudeosaar-api
        tier: backend
    spec:
      containers:
      - name: api
        image: claudeosaar/api:latest
        ports:
        - containerPort: 6600
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: claudeosaar-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: claudeosaar-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: claudeosaar-secrets
              key: jwt-secret
        - name: CLAUDE_API_KEY
          valueFrom:
            secretKeyRef:
              name: claudeosaar-secrets
              key: claude-api-key
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: claudeosaar-secrets
              key: stripe-secret-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 6600
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 6600
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: claudeosaar-api
  namespace: claudeosaar
spec:
  selector:
    app: claudeosaar-api
  ports:
  - port: 6600
    targetPort: 6600
  type: ClusterIP