apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: claudeosaar-api-hpa
  namespace: claudeosaar
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: claudeosaar-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "1000"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: claudeosaar-ui-hpa
  namespace: claudeosaar
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: claudeosaar-ui
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: claudeosaar-mcp-hpa
  namespace: claudeosaar
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: claudeosaar-mcp
  minReplicas: 2
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80