apiVersion: apps/v1
kind: Deployment
metadata:
  name: claudeosaar-mcp
  namespace: claudeosaar
  labels:
    app: claudeosaar-mcp
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: claudeosaar-mcp
  template:
    metadata:
      labels:
        app: claudeosaar-mcp
        tier: backend
    spec:
      containers:
      - name: mcp-server
        image: claudeosaar/mcp-server:latest
        ports:
        - containerPort: 6602
        env:
        - name: NODE_ENV
          value: "production"
        - name: CLAUDE_API_KEY
          valueFrom:
            secretKeyRef:
              name: claudeosaar-secrets
              key: claude-api-key
        volumeMounts:
        - name: workspace-storage
          mountPath: /user_mounts
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 6602
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 6602
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: workspace-storage
        persistentVolumeClaim:
          claimName: workspace-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: claudeosaar-mcp
  namespace: claudeosaar
spec:
  selector:
    app: claudeosaar-mcp
  ports:
  - port: 6602
    targetPort: 6602
  type: ClusterIP