apiVersion: v1
kind: Secret
metadata:
  name: claudeosaar-secrets
  namespace: claudeosaar
type: Opaque
stringData:
  database-url: "postgresql://claude:password@postgres:5432/claudeosaar"
  db-password: "your-secure-db-password"
  redis-url: "redis://:password@redis:6379"
  redis-password: "your-secure-redis-password"
  jwt-secret: "your-jwt-secret-key"
  claude-api-key: "your-anthropic-api-key"
  stripe-secret-key: "your-stripe-secret-key"
  stripe-public-key: "your-stripe-public-key"
  
# Note: In production, use sealed-secrets or external secret management